#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH="$DIR:$PATH"
cd "$DIR/.."
echo "Running tests..."
python /Users/Alex/Documents/Developer/swift-src/llvm/utils/lit/lit.py -sv ./test