#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH="$DIR:$PATH"
cd "$DIR/.."
echo "Running tests..."
UTILS_DIR=$( dirname "${BASH_SOURCE[0]}" )
echo $UTILS_DIR
python "$UTILS_DIR/lit/lit.py" -sv ./test
